### ISSUE TITLE
Question: will this work on Android

### ISSUE THREAD

**Issue by QiangF** [snyball/Hawck#11]
Now it's quite easy to run emacs with termux on Android. Since Android uses the linux kernel, doesn't that mean the answer is Yes?

**Comment by QiangF** [comment]
This one is cool
https://github.com/sds100/KeyMapper/

**Comment by snyball** [comment]
Might be possible.
Hawck uses Linux-specific `ioctl` calls, [uinput](https://www.kernel.org/doc/html/latest/input/uinput.html) for keyboard control, and [inotify](https://android.googlesource.com/kernel/common/+/bcmdhd-3.10/Documentation/filesystems/inotify.txt) for listening to file system events. All of which should be supported on Android.
You'd most likely need root-access to install and use it however.
