### ISSUE TITLE
Can't replace Caps Lock

### ISSUE THREAD

**Issue by rudolfkral** [snyball/Hawck#20]
Hi,

I can't replace the Caps Lock key using my script:
```
require "init"

key "caps" => replace "escape"
```
The result:
```
lua5.3: ./LLib/Keymap.lua:310: No such key: caps
stack traceback:
	[C]: in function 'error'
	./LLib/Keymap.lua:310: in function 'Keymap.getKeysym'
	(...tail calls...)
	./LLib/Hawck.lua:69: in function 'key'
	/home/.../.local/share/hawck/scripts/colemak.lua:3: in main chunk
	[C]: in ?
```

I have tried "Caps_Lock", I've tried looking at the code and changing selected keymaps around, to no avail, there just is no Caps Lock. I don't know Lua, so my debugging skills are limited here. Do you maybe know what's happening?

**Comment by snyball** [comment]
Have you tried:

```lua
-- Note the caps on Caps, caps
key "Caps" => replace "Escape"
```

Also, you don't need `require "init"` at the top.

I really need to get around to updating the documentation, as well as making those keys case-insensitive (busy with university assignments atm unfortunately.)

PS: nice profile picture, that's one of my favorite paintings.

**Comment by rudolfkral** [comment]
Thank you! Caps with a big "C" works. I can't get to work around @ and ", I'll look in README and 

I am on master branch. I compeletely understand your being busy, I can send some things that don't work for me here, and send a PR to fix them if eligible. My biggest problem is lack of know-how around Lua ecosystem, but once I get everything working everything should be cool.

Can I suggest adding minimal versions of some dependencies to the README? I had to update my GCC and Ruby accordingly. Also, there are still lowercap Caps and Escape in the README. I can include it in a PR if that would help.

In general, is it possible to list programatically all labels that Hawck can match, like "Escape", "Caps" etc? I tried looking around xkb and linux maps, but I'm still too confused to find it perhaps.

Thanks again for this project, I really needed a neat replacement for xmodmap!

**Comment by rudolfkral** [comment]
Sorry for adding info here, but I have to ask and I wouldn't like to spam the issues board.

I'm using xkb colemak us setup in `/etc/default/keyboard`. It supposedly maps Caps to Ctrl_L. Does that mean that Hawck never actually gets the Caps keycode, so it can't distinguish between "physical" Ctrl_L and one emulated by xkb?

I'm not aware that I can turn off xkb completely, I assume I should switch to a normal us keyboard and everything should work?

**Comment by snyball** [comment]
Hawck doesn't really use `xkb` at all, it reads from the Linux console keymaps exclusively, you just have to make sure that the keymap used by Hawck is the same one used by your desktop environment.

Since you're using the master-branch, I recently changed where scripts are placed and how they are activated. You no longer need the `install` shell script.

```sh
$ vim .config/hawck/scripts/my_script.hwk
## Enable the script
$ chmod 0755 .config/hawck/scripts/my_script.hwk
## Disable the script
$ chmod -x .config/hawck/scripts/my_script.hwk
```

Error/info messages should appear as desktop notifications, but they are also logged with `syslog` (`journalctl -xe | grep hawck`)

For testing things out, you can also do this:

```sh
$ sudo cp Hawck/bin/__UNSAFE_MODE.csv /var/lib/hawck-input/keys/
```

Which will whitelist all the keys, so that everything is passed from `inputd` to `macrod`.

For listing keys you can put the following snippet into `~/.local/share/hawck/scripts/print_keys.lua`

```lua
require "init" -- Required in this case, because we're running it directly
local kbmap = require "Keymap"
local keys = kbmap.new("<your keymap code here, e.g no, de, us, pl>")
u.puts(keys.keymap)
```

And run it directly using `lua`

```sh
$ cd ~/.local/share/hawck/scripts
$ cat > print_keys.lua
<paste snippet>
$ lua print_keys.lua
```

Hope that helps.

**Comment by rudolfkral** [comment]
Thank you, so I noticed a few things:

1. Some keyboards don't have particular keys in their keymap. For example, there is no "numbersign" nor "asciitilde" for us keymap. With a hawck script like:

```
shift + key "3" => replace "numbersign"
```

It, of course, doesn't know what numbersign is. Is there a possibility of making it know without changing the keymap? Does Hawck know only the characters present in the keymap?

When I do something like this:

```
shift + key "3" => replace "#"
```

Nothing changes. No messages in journal, no errors. Just old key(£ on my keyboard).

2. Another example. Currently my shift + "2" prints '"'(the double quote). When I do something like:

```
shift + key "2" => replace "@"
```

Whenever I press shift + "2", nothing changes. But when I do this:

```
shift + key "2" => write("@")
```

This happens: whenever I press shift + "2", I get two double quotes!

3. The most strange thing. With my script being

```
key "Caps" => replace "Escape"
shift + key "2" => replace "@"
```

and UNSAFE_MODE unblocking all keys from inputd, I get very strange results. When I press shift alone and hold it, I get a row of tildes(~) and hashes(#) racing against each other!

I'm debugging it step by step, but maybe you have seen such a thing? Tilde and hash are currently mapped to one key(tilde = shift + hash), which is NOT either of keys I tried to replace.

Something's definitely got mixed up here. I don't have xmodmap activated. My xkb is uk-colemak, but you said that xkb is not relevant here. If Hawck gets confused with my settings, how did I do that? :D

**Comment by snyball** [comment]
I missed something in the previous code snippet, here's the correct version:

```lua
require "init"
local kbmap = require "Keymap"
local keys = kbmap.new("uk-colemak")
u.puts(keys.keymap)
u.puts(keys.combo_map) -- Note this added line
```

The line added at the end there is where you should find "numbersign", "exclam", etc.

Also, you can try
```lua
shift + key "3" => off -- should result in nothing happening when pressing S-3
```

To see if there's just a problem getting a `shift + key "3"` activation.

Also make sure to edit `~/.local/share/hawck/cfg.lua` so that it says:

```lua
local config = {
  keymap = "uk-colemak", -- edit this one
  disable_on_err = false,
  eval_keyup = true,
  eval_keydown = true,
  eval_repeat = true,
  disabled = false,
  notify_on_err = false,
}
return config
```

The `replace` function should not be used with keys that require modifiers, only with single keys. The `write` version should work, but there's probably a mixup with the two keymaps creating problems. You could also try:

```lua
down + shift + key "2" => off
up + shift + key "2" => insert "@"
```

**Comment by rudolfkral** [comment]
Thank you again. I changed my keymap from colemak-uk to colemak-us, in /etc/default/keyboard as well as in hawck, and now everything works as expected. It must have been a quirk about UK layout, but I have no idea what exactly.

**Comment by snyball** [comment]
@rudolfkral Nice, then I'll close this.
