### ISSUE TITLE
Is it possible to use hawck as screenkey

### ISSUE THREAD

**Issue by albfan** [snyball/Hawck#21]
Can we create a script that render a black rectangle and the key pressed on top of it?

Any other enhancement (rectangle transparency, show several keys pressed) can be tackle later if this basic functionality is possible.

This tries to be a workaround for screenkey, which do not support wayland https://www.thregr.org/~wavexx/software/screenkey/#no-output-when-using-gnome-terminal-in-wayland

**Comment by snyball** [comment]
Yeah, that should be possible.

First enable unsafe mode by copying the `__UNSAFE_MODE.csv` file into `/var/lib/hawck-input/keys`, then write a script like this:

```lua
-- Note the lack of error-handling as this is only an example.
fifo_path = u.expandEnv("$XDG_RUNTIME_DIR/keys.fifo")
os.execute("mkfifo " .. u.shescape(fifo_path))
fifo = io.open(fifo_path)
-- NOTE: Be careful about using `any`, if the kbd:echo() isn't there
--       it will silence the keyboard
any => function ()
  fifo:write(kbd.event_code)
  fifo:write(" ")
  fifo:write(kbd.event_value)
  fifo:write(" ")
  fifo:write(kbd.event_type)
  fifo:write("\n")
  fifo:flush()
  kbd:echo()
end
```

Then have your display application listen on that fifo:

```sh
$ display-keys < "$XDG_RUNTIME_DIR/keys.fifo"
```

That's probably the easiest way to do this.

**Comment by albfan** [comment]
I tried to add the script with hawck-add but the command didn't end (as when I add the /etc/hawck/scripts/example.hwk) I tried to put a `require "init"` but nothing changes.

**Comment by albfan** [comment]
After put file in `~/.config/hawck/scripts` it starts to work.

But io.open is a blocking operation, so I modify the script to show the keystrokes:

```
$ cat ~/.config/hawck/scripts/screenkey.hwk 
any => function ()
  et = kbd.event_type
  if et == 0 then ets = 'UP'
  elseif et == 1 then ets = 'DOWN'
  elseif et == 2 then ets = 'REPEAT'
  end
  u.puts(kbd.event_code .. ', ' .. kbd.event_value .. ', ' .. ets)
  kbd:echo()
end
```

which outputs: (for <kbd>a</kbd>,<kbd>s</kbd>,<kbd>d</kbd>,<kbd>f</kbd>,<kbd>F1</kbd>,<kbd>F2</kbd>,<kbd>F3</kbd>,<kbd>F4</kbd>)

```
$ hawck-macrod --no-fork
"0, 0, UP"
"4, 30, UP"
"30, 1, DOWN"
"0, 0, UP"
a"4, 30, UP"
"30, 0, DOWN"
"0, 0, UP"
"4, 31, UP"
"31, 1, DOWN"
"0, 0, UP"
s"4, 31, UP"
"31, 0, DOWN"
"0, 0, UP"
"4, 32, UP"
"32, 1, DOWN"
"0, 0, UP"
d"4, 32, UP"
"32, 0, DOWN"
"0, 0, UP"
"4, 33, UP"
"33, 1, DOWN"
"0, 0, UP"
f"4, 33, UP"
"33, 0, DOWN"
"0, 0, UP"
"4, 59, UP"
"59, 1, DOWN"
"0, 0, UP"
^[OP"4, 59, UP"
"59, 0, DOWN"
"0, 0, UP"
"4, 60, UP"
"60, 1, DOWN"
"0, 0, UP"
^[OQ"4, 60, UP"
"60, 0, DOWN"
"0, 0, UP"
"4, 61, UP"
"61, 1, DOWN"
"0, 0, UP"
^[OR"4, 61, UP"
"61, 0, DOWN"
"0, 0, UP"
"4, 62, UP"
"62, 1, DOWN"
"0, 0, UP"
^[OS"4, 62, UP"
"62, 0, DOWN"
"0, 0, UP"
"4, 29, UP"
"29, 1, DOWN"
"0, 0, UP"
"4, 46, UP"
"46, 1, DOWN"
"0, 0, UP"
^C
```

I think I can read this output

    $ display-keys <(hawck-macrod --no-fork)

but wonder if the fifo can be done in some way and a better parseable representation of a key

**Comment by snyball** [comment]
@albfan You can use `require "json"` for that, it has a serialization function:

```lua
local json = require "json"
local ss = json.sstream.new()
json.serialize(kbd, ss)
print(ss:get())
```

**Comment by albfan** [comment]
Nice, it looks basically as:

```
local json = require "json"
local ss = json.sstream.new()

any => function ()

  et = kbd.event_type
  ec = kbd.event_code
  ev = kbd.event_value

  key = {code = ec, type = et, value = ev }
  json.serialize(key, ss)
  print(ss:get())

  kbd:echo()
end
```

But is too low level. Not sure how to process combos etc, is there any doc for kbd? I think it has functions to report directly Ctrl+A etc

**Comment by snyball** [comment]
@albfan There are two ways to handle that.

1. Track the state of modifiers inside the display application, so inside the application responsible for drawing the key-presses you'll have something like this pseudocode:
```c++
if (code == ctrl) modifiers.ctrl.is_down = (val != KeyUp)
// Format
string out;
for (modifier : modifiers) {
  out.append(modifer.name + "+");
}
out.append(keyName(code));
```
2. Do it inside the script, hawck scripts already keep track of the state of modifier keys.
```lua
-- Untested, but you want something like this
function formatCurrentKey()
  local modifiers = {ctrl, alt, shift}
  local modifier_names = {"ctrl", "alt", "shift"}
  local out = ""
  for i, v in ipairs(modifiers) do
    if v() then
      out = out .. modifier_names[i] .. "+"
    end
  end
  return out .. kbd.map.keymap[code]
end
```

**Comment by albfan** [comment]
Got it. I will play around with that, thank!

**Comment by albfan** [comment]
FTR, maybe this could be added as another example

```
local json = require "json"
local ss = json.sstream.new()

any => function ()
  etype = kbd.event_type
  ecode = kbd.event_code
  evalue = kbd.event_value

  if etype == 1 then
    local m
    if evalue == 0 then
      m = "UP"
    elseif evalue == 1 then
      m = "DOWN"
    elseif evalue == 2 then
      m = "REPEAT"
    end

    key = {code = formatKey(ecode), mode = m }
    json.serialize(key, ss)
    print(ss:get())
  else
    key = {code = ecode, value = evalue, type = etype }
    json.serialize(key, ss)
    print(ss:get())
  end

  kbd:echo()
end

function formatKey(code)
  local modifiers = {ctrl, alt, shift}
  local modifier_names = {"ctrl", "alt", "shift"}
  local out = ""
  for i, v in ipairs(modifiers) do
    if v() then
      out = out .. modifier_names[i] .. "+"
    end
  end
  return out .. kbd.map.keymap[code]
end
```

which output (<kbd>a</kbd>,<kbd>Ctrl</kbd>+<kbd>a</kbd>):

```
{
  "code": "a",
  "mode": "UP"
}
{
  "code": "a",
  "mode": "UP"
}
{
  "code": "ctrl+a",
  "mode": "UP"
}
{
  "code": "ctrl+a",
  "mode": "DOWN"
}

```

I'm not sure about special keys (this is raw output from volume mute/up/down):

```
{
  "value": 160,
  "code": 4,
  "type": 4
}
{
  "value": 176,
  "code": 4,
  "type": 4
}
{
  "value": 174,
  "code": 4,
  "type": 4
}
```

**Comment by snyball** [comment]
@albfan I'm working on a scripts collection to distribute with the Hawck installation, and I'll definitely add the key-press printer as an example.

I can't do it right now however, as there is a blocking feature needed, called passthrough-scripts. Once passthrough-scripts are implemented, I can add the printer script to the collection.

**Comment by albfan** [comment]
Cool!. Just let me know and I will improve when I identify more special keys. Example:

vol keys for screenkey:
- https://gitlab.com/screenkey/screenkey/-/blob/master/Screenkey/labelmanager.py#L80
- https://gitlab.com/screenkey/screenkey/-/blob/master/Screenkey/labelmanager.py#L84
- https://gitlab.com/screenkey/screenkey/-/blob/master/Screenkey/labelmanager.py#L86

etc...
