### ISSUE TITLE
services need to follow prefix

### ISSUE THREAD

**Issue by albfan** [snyball/Hawck#22]
https://github.com/snyball/Hawck/blob/master/bin/hawck-inputd.service#L11
https://github.com/snyball/Hawck/blob/master/bin/hawck-macrod.service#L7

always try to run /usr/local but `meson --prefix whatever` should be followe

https://mesonbuild.com/Configuration.html

```
conf = configuration_data()
conf.set_quoted('PREFIX', get_option('prefix'))
configure_file(
  input: 'hawck-inputd.service.in'
  output: 'hawck-inputd.service',
  configuration: conf
)
```

**Comment by snyball** [comment]
Damn, I completely overlooked this, nice catch. 

If you send a PR I'll get it merged right away.
