### ISSUE TITLE
Checking everything is in place

### ISSUE THREAD

**Issue by albfan** [snyball/Hawck#23]
```
$ systemctl status hawck-inputd.service 
● hawck-inputd.service - Hawck input daemon
     Loaded: loaded (/usr/lib/systemd/system/hawck-inputd.service; enabled; vendor >
     Active: active (running) since Wed 2020-04-01 22:34:35 CEST; 17min ago
    Process: 10400 ExecStart=/usr/bin/hawck-inputd --no-hotplug (code=exited, statu>
   Main PID: 10402 (hawck-inputd)
      Tasks: 3 (limit: 9345)
     Memory: 900.0K
     CGroup: /system.slice/hawck-inputd.service
             └─10402 /usr/bin/hawck-inputd --no-hotplug

abr 01 22:44:19 archlinux-alberto hawck-inputd[10402]: SystemError: Connection refu>
abr 01 22:44:19 archlinux-alberto hawck-inputd[10402]: Locking keyboard: AT Transla>
abr 01 22:44:19 archlinux-alberto hawck-inputd[10402]: Immediate lock on: AT Transl>
```
```
$ systemctl status --user hawck-macrod.service
● hawck-macrod.service - Hawck Macro Daemon
     Loaded: loaded (/usr/lib/systemd/user/hawck-macrod.service; disabled; vendor p>
     Active: active (running) since Wed 2020-04-01 22:44:19 CEST; 8min ago
       Docs: man:hawck-macrod(1)
   Main PID: 10931 (hawck-macrod)
     CGroup: /user.slice/user-1000.slice/user@1000.service/hawck-macrod.service
             └─10931 /usr/bin/hawck-macrod --no-fork

abr 01 22:44:19 archlinux-alberto systemd[623]: Started Hawck Macro Daemon.
abr 01 22:44:19 archlinux-alberto hawck-macrod[10931]: Outdated pid file with exe '>
abr 01 22:44:19 archlinux-alberto hawck-macrod[10931]: Registered inotify instance >
abr 01 22:44:19 archlinux-alberto hawck-macrod[10931]: Setting up MacroDaemon ...
abr 01 22:44:19 archlinux-alberto hawck-macrod[10931]: Listening for a connection .>
abr 01 22:44:19 archlinux-alberto hawck-macrod[10931]: Resetting fifo
abr 01 22:44:19 archlinux-alberto hawck-macrod[10931]: Got a connection
abr 01 22:44:19 archlinux-alberto hawck-macrod[10931]: Starting main loop
```

And have installed example and script in #21 

```
$ ls -1 ~/.local/share/hawck/scripts/
example.hwk
example.lua
init.lua
keymaps
LLib
screenkey.lua
```

but nothing happens on fifo or pressing <kbd>Ctrl</kbd>+<kbd>Alt</kbd>+<kbd>h</kbd>

Is there a way to check if hawck-macrod is listening correctly? like xev or similar

**Comment by snyball** [comment]
You can write a script to print out `any` key, like this:

```lua
any => function ()
  u.puts(kbd)
  kbd:echo()
end
```

In order to see those `u.puts` prints you'll need to run the macro daemon like this:

```sh
$ hawck-macrod --no-fork
```

When forking, macrod will redirect output to `/dev/null`, when `--no-fork` is passed, it will print out to `stdout` like normal.

**Comment by albfan** [comment]
Yep. `hawck-macrod.service` runs `hawck-macrod` with `--no-fork`

I run from command line directly and I can see the log for `hawck-inputd`:

```
abr 04 02:47:26 archlinux-alberto hawck-inputd[4852]: Locking keyboard: AT Translated Set 2 keyboard ...
abr 04 02:47:26 archlinux-alberto hawck-inputd[4852]: Preparing async lock on: AT Translated Set 2 keyboard @ isa0060/serio0/input0
abr 04 02:47:27 archlinux-alberto hawck-inputd[4852]: Acquired lock on keyboard: AT Translated Set 2 keyboard
```

I installed that script with `hawck-add` and it installs:

```
$ cat ~/.local/share/hawck/scripts/echo.lua 
__match[any] = function ()
  u.puts(kbd)
  kbd:echo()
end
```

I remove any other script, restarted `hawck-inputd` and `hawck-macrod` but can't see any output..

Not sure if I can provide any other info to understand what's happening

**Comment by snyball** [comment]
Don't install it with `hawck-add`, put it in `~/.config/hawck/scripts` and set `chmod 0755`.

**Comment by albfan** [comment]
Nice, I start to see things. If I can improve doc will send a PR

**Comment by aemino** [comment]
Hi, I have a similar setup (both hawck-inputd and hawck-macrod running systemd services) but I can't get hawk scripts to be functional. The daemons seem to be functional; I see `Starting main loop` and `Running Hawck InputD`, but I never see anything about locking a keyboard--perhaps it isn't being detected? I'm using Wayland (sway) on Arch Linux.

**Comment by snyball** [comment]
@aemino The keyboard-detection in Hawck is somewhat brittle, post a new issue and include the output of the following commands

```bash
$ ls -Al /dev/input/by-id
$ ls -Al /dev/input/by-path
$ ls -Al /dev/input
```

Also include information about the specific kind of keyboard, whether it is external (USB/PS2) or internal (laptop built-in.)

If you know the specific device file in `/dev/input/event${n}` that corresponds to your keyboard, try starting `hawck-inputd` manually with `hawck-inputd --kbd-device /dev/input/event${n}`
