### ISSUE TITLE
master seems to be unbuildable from AUR

### ISSUE THREAD

**Issue by nperry** [snyball/Hawck#25]
> FAILED: src/25a6634@@hawck-chroot@exe/hawck-chroot.c.o 
ccache cc -Isrc/25a6634@@hawck-chroot@exe -Isrc -I../src -fdiagnostics-color=always -pipe -D_FILE_OFFSET_BITS=64 -Wall -Winvalid-pch -std=c18 -g -march=x86-64 -mtune=generic -O2 -fno-plt -D_FORTIFY_SOURCE=2 -MD -MQ 'src/25a6634@@hawck-chroot@exe/hawck-chroot.c.o' -MF 'src/25a6634@@hawck-chroot@exe/hawck-chroot.c.o.d' -o 'src/25a6634@@hawck-chroot@exe/hawck-chroot.c.o' -c ../src/hawck-chroot.c
../src/hawck-chroot.c:9:1: error: unknown type name 'pid_t'
    9 | pid_t MACROD_PID;
      | ^~~~~
../src/hawck-chroot.c:10:1: error: unknown type name 'pid_t'
   10 | pid_t INPUTD_PID;
      | ^~~~~
../src/hawck-chroot.c:12:1: error: unknown type name 'uid_t'
   12 | uid_t uidof(const char *user)
      | ^~~~~
../src/hawck-chroot.c: In function 'uidof':
../src/hawck-chroot.c:14:5: error: unknown type name 'uid_t'
   14 |     uid_t ret = -1;
      |     ^~~~~
../src/hawck-chroot.c:28:13: warning: implicit declaration of function 'getpwnam_r'; did you mean 'getpwnam'? [-Wimplicit-function-declaration]
   28 |     int s = getpwnam_r(user, &pwd, buf, bufsz, &result);
      |             ^~~~~~~~~~
      |             getpwnam
../src/hawck-chroot.c: At top level:
../src/hawck-chroot.c:45:1: error: unknown type name 'pid_t'
   45 | pid_t runuser(const char *destdir,
      | ^~~~~
../src/hawck-chroot.c: In function 'runuser':
../src/hawck-chroot.c:50:5: error: unknown type name 'pid_t'
   50 |     pid_t pid;
      |     ^~~~~
../src/hawck-chroot.c:59:17: warning: implicit declaration of function 'chroot' [-Wimplicit-function-declaration]
   59 |                 chroot(destdir);
      |                 ^~~~~~
../src/hawck-chroot.c: In function 'main':
../src/hawck-chroot.c:82:5: error: unknown type name 'pid_t'
   82 |     pid_t macrod_pid = runuser(destdir, "hawck-test-user", "hawck-macrod", macrod_argv);
      |     ^~~~~
../src/hawck-chroot.c:83:5: error: unknown type name 'pid_t'
   83 |     pid_t inputd_pid = runuser(destdir, "hawck-input", "hawck-inputd", inputd_argv);
      |     ^~~~~
../src/hawck-chroot.c:88:5: error: unknown type name 'sigset_t'; did you mean 'size_t'?
   88 |     sigset_t sigset;
      |     ^~~~~~~~
      |     size_t
../src/hawck-chroot.c:90:5: warning: implicit declaration of function 'sigfillset' [-Wimplicit-function-declaration]
   90 |     sigfillset(&sigset);
      |     ^~~~~~~~~~
../src/hawck-chroot.c:91:5: warning: implicit declaration of function 'sigwait' [-Wimplicit-function-declaration]
   91 |     sigwait(&sigset, &sig);
      |     ^~~~~~~
../src/hawck-chroot.c:95:9: warning: implicit declaration of function 'kill' [-Wimplicit-function-declaration]
   95 |         kill(macrod_pid, SIGKILL);
      |         ^~~~
../src/hawck-chroot.c: In function 'runuser':
../src/hawck-chroot.c:60:13: warning: ignoring return value of 'setuid', declared with attribute warn_unused_result [-Wunused-result]
   60 |             setuid(uid);
      |             ^~~~~~~~~~~

Let me know if anything else is needed?

**Comment by su8** [comment]
He forgot to add **sys/types.h** header and for chroot and kill declarations he can use **#define _POSIX_SOURCE** or x open source instead.

**Comment by snyball** [comment]
Sorry about this, I've fixed this as of 7ae849750d222d86abf52952977977b669e1c01e by hiding unfinished tests/tools behind a `development_build` build option.

`hawck-chroot` should never have been in the default build, it is not required for the rest of the system to work.

**Comment by snyball** [comment]
The build is working for me now,  tentatively closing this.

**Comment by nperry** [comment]
confirming all built now, thanks!
