### ISSUE TITLE
meson_options.txt:6:0: ERROR: Option name debug is reserved.

### ISSUE THREAD

**Issue by colemickens** [snyball/Hawck#3]
It seems that in newer versions of meson, `debug` is a reserved option name. This blocks my packaging of it for NixOS via "nixpkgs-wayland".

**Comment by snyball** [comment]
I'll have a look at it in the morning, should only require changing two of the meson files replacing debug with debug_hawck.

**Comment by snyball** [comment]
You might also want to have a look into issue #4

**Comment by snyball** [comment]
Issue should now be resolved, moving on to issue #4 to clear up more packaging difficulties.

**Comment by MatrixManAtYrService** [comment]
@colemickens I'd like to use this in NixOS, did you end up succeeding?  (nixpkgs search didn't turn it up)
