### ISSUE TITLE
Fixing compilation on Fedora 32

### ISSUE THREAD

**Issue by jamespo** [snyball/Hawck#31]
On F32 I needed to add '#include <string>' to src/KBDB.cpp & src/KBDB.hpp

Just FYI

**Comment by snyball** [comment]
You had to `#include <what.h>`?

**Comment by jamespo** [comment]
Whoops sorry, didn't realise anything between angled brackets would be gobbled

`#include <string>`

**Comment by snyball** [comment]
Should be fixed as of 02dda96, thanks for the report.
