### ISSUE TITLE
Unable to find keymaps directory on Fedora 32

### ISSUE THREAD

**Issue by elmehalawi** [snyball/Hawck#34]
I'm pretty sure I did something stupid so please excuse me. When I try to add a Hawck script, I get the following error:

```
$ hawck-add ~/.config/hawck/scripts/example.hwk 
lua5.3: ./LLib/Keymap.lua:261: Unable to find keymaps directory.
stack traceback:
	[C]: in function 'error'
	./LLib/Keymap.lua:261: in function 'Keymap.getall'
	./LLib/Keymap.lua:281: in function 'Keymap.new'
	./LLib/kbd.lua:36: in main chunk
	[C]: in function 'require'
	./LLib/Hawck.lua:35: in main chunk
	[C]: in function 'require'
	./init.lua:2: in main chunk
	[C]: in function 'require'
	[C]: in ?

```

The two directories it's looking through don't exist though. I tried adding another directory [after this line](https://github.com/snyball/Hawck/blob/998276f8c373fd9a1c52773809b61cec538f24d0/src/Lua/Keymap.lua#L250). I found some keymaps in "/usr/share/ibus/keymaps" (including the "us" keymap, which is the one I'm interested in; I'm using an unmodified "us" layout), so that's the path I added. Now it gives me this error:

```
$ hawck-add ~/.config/hawck/scripts/example.hwk 
lua5.3: ./LLib/Keymap.lua:284: No such keymap: no
stack traceback:
	[C]: in function 'error'
	./LLib/Keymap.lua:284: in function 'Keymap.new'
	./LLib/kbd.lua:36: in main chunk
	[C]: in function 'require'
	./LLib/Hawck.lua:35: in main chunk
	[C]: in function 'require'
	./init.lua:2: in main chunk
	[C]: in function 'require'
	[C]: in ?

```

Looks like it's checking for Norwegian, but it's not in that directory. Not sure if there's another place on Fedora 32 that has all the keymaps. Is the above behavior of crashing when not finding Norwegian a bug?

**Comment by snyball** [comment]
Did you edit `~/.local/share/hawck/cfg.lua`?

```lua
$ cat ~/.local/share/hawck/cfg.lua                                                                                                               local config = {
  keymap = "us", -- You want to change this line
  disable_on_err = false,
  eval_keyup = true,
  eval_keydown = true,
  eval_repeat = true,
  disabled = false,
  notify_on_err = false,
}
return config
```

**Comment by snyball** [comment]
Also, at least on Debian/Ubuntu you need to install a package in order to get the console keymaps, I don't know if that's the case on Fedora as I've never used it. But that's one thing you could look into.

You definitely haven't done anything stupid, none of this is standardized, so it's a bit of a pain to make it work across many distros. I think from now on I'll just bundle the console keymaps together with Hawck to keep this issue from popping up, I'll reference this issue when I get that done.

**Comment by silenc3r** [comment]
I think that on Fedora keymaps are located at `/lib/kbd/keymaps/`.

**Comment by elmehalawi** [comment]
@silenc3r I see a lot of .map.gz files inside `/lib/kbd/keymaps/xkb`. Are these the keymap files?

**Comment by snyball** [comment]
@elmehalawi If adding that keymap directory works on Fedora, then a pull request for it would be welcome.

Sorry for the late response.
