### ISSUE TITLE
Text expand with phrases [Feature Request]

### ISSUE THREAD

**Issue by jacostag** [snyball/Hawck#35]
**Feature Request**
1. Type a phrase like "mypass1"

**Expected behavior**
1. Auto delete and paste the real phrase: "MyPassw0rd!"

**Comment by snyball** [comment]
@jacostag This sounds cool, and is possible to do with a script, but I'm hesitant to add it to hawck for a couple of reasons:

1. It encourages storing passwords with Hawck, which should really be handled with a proper password manager.
    - It also has other uses, but this seems to be the primary use-case for this feature request
2. The only way to make this work is to continuously log key presses (at least as many as the longest source string) which I also don't like.

If you would like this feature, this is how to accomplish it:

```lua
ring_buf = RingBuffer:new(32)

any => function ()
  local str = "mystring"
  local replace_with = "other_string"
  if ring_buf:endswith(str) then
    kbd:withCleanMods(function ()
        for i = 1, #str do
          -- FIXME: Backspace, I just noticed that it isn't being detected in
          -- the keymaps, so as a workaround the key-code is emitted manually
          -- (it maps to the number 14 on most keyboards)
          kbd:emit(1, 14, 1)
          kbd:emit(1, 14, 0)
        end
    end)
    write(replace_with)()
    ring_buf:clear()
  else
    ring_buf:push(kbd:getKeySym(kbd.event_code))
  end
  kbd:echo()
end
```

Where `RingBuffer` is left as an exercise to the reader.

**Comment by jacostag** [comment]
Thank you, I will try this.
The autoexpand text might be used for passwords, but also for things like your email, or an address, etc

**Comment by knezi** [comment]
> 
> 1. It encourages storing passwords with Hawck, which should really be handled with a proper password manager.
>    
Storing passwords is not a good idea, but there are many other uses. Like:

```
VBW -> Very best wishes
```

```
jo@ -> john@doe.com
```

or even if you work with many servers through SSH:

```
gc -> git commit
```

All this could be accomplished with aliases, abbr in vim and such, but it seems to be very conveniently stored here at one place working everywhere.

Anyway, thanks for the snippet.
