### ISSUE TITLE
Option desktop_user not defined

### ISSUE THREAD

**Issue by travankor** [snyball/Hawck#4]
I am trying to build hawck-ui for Void Linux's repos, but the build script for hawck-ui doesn't seem to work inside an isolated chroot build.

Having bash scripts inside the meson build is counter-productive for packagers, since account creation and things like that are best handled by the package manager (at least, for Void Linux and Guix). Also, the binary package builder for Void won't have `desktop_user` set for Meson anyways.

It would be nice if hawck-ui used pure meson for building.

**Comment by snyball** [comment]
Sounds good, the current build code was optimized for people doing meson install, as a convenience while there were no packages. 

I'll first refactor the install script to separate the desktop user stuff from the system stuff. Then I'll disable it from the default build. After that meson should only install the binaries, and man pages. 

I'll keep the meson install as a backup option that has to be configured with a use_meson_install option. 

Does this sound like a good way forward?

**Comment by snyball** [comment]
Solved as of the last commit.
