### ISSUE TITLE
No security by default?

### ISSUE THREAD

**Issue by abitrolly** [snyball/Hawck#41]
From https://github.com/snyball/Hawck/blob/841e563a3be93fbc1e0f9d428a08191f576201a5/README.md#security

> The keyboard daemon contains a whitelist of keys that the macro daemon is allowed to see, this whitelist is derived from the Lua scripts used.

But Lua scripts are user controlled. Does that mean that user is still able to read all keyboard input?

**Comment by snyball** [comment]
No, you need to run `hawck-add`, which will ask for elevated priviliges (via `sudo` or `pkexec`.)

**Comment by abitrolly** [comment]
And when `hawck-add` adds the script, the keys that are whitelisted can be read by any user level program, right?

**Comment by snyball** [comment]
@abitrolly Yes

Alternative approaches and motivations for the current model can be found here: https://github.com/snyball/Hawck#alternative-security-strategies-and-motivations

**Comment by abitrolly** [comment]
Thanks. Now it is clear. I did read that paragraph, but could not understand.
