### ISSUE TITLE
Ask permission to intercept keys for a given app

### ISSUE THREAD

**Issue by abitrolly** [snyball/Hawck#42]
I would feel more comfortable if I could explicitly allow a certain process to access key listening capabilities of Hawck. Using some system mechanism similar to a dialog request for elevated privileges to reduce attack surface.

**Comment by snyball** [comment]
I'm not entirely sure what you mean by this, but I think what you want is to just run `macrod` as a different user-account.

Allowing access to keys on a per-process basis can be accomplished by running that process under a particular user, afaik you can't really have per-process granularity for a single user on Linux, because of `/proc/...`, `ptrace` etc. Those can be disabled, but I don't want the security-model to fall apart as soon as a user needs to attach `gdb` onto a running program, and thus has to enable `ptrace` again.

**Comment by snyball** [comment]
@abitrolly If instead, what you want is something like "only intercept keys that are going to applications Gimp, Emacs, and Foo" this cannot be accomplished currently. Hawck would need a `getCurrentFocusedWindow()` function with separate implementations for X11, Console, and not just Wayland, but different Wayland compositors (afaik there's no widely deployed standard for how to do this on Wayland yet.)

**Comment by abitrolly** [comment]
I was asking for a mechanism described in https://github.com/snyball/Hawck/issues/41#issuecomment-693367307 and since the mechanism to ask for elevated privileges is already in place, the missing part is filtering key stream by listener and by target process(es).

> afaik you can't really have per-process granularity for a single user on Linux, because of /proc/..., ptrace etc

I am not well aware of how Linux detect which keys are sent to which process. I thought there is a `controlling terminal` and the `Hawck` part that runs under root can see the process, to which this `contolling terminal` is attached to make a decision if its keys can be intercepted.

The same logic with the listener - when elevated privileges are requested, the `Hawck` can inspect listener process tree to decide if listener is legit.

**Comment by snyball** [comment]
@abitrolly The model is explained here: https://github.com/snyball/Hawck#security

Keyboard input roughly follows this trail with Hawck running: `Keyboard -> Linux Kernel -> hawck-inputd -> udev -> wayland compositor (uinput) -> application`. Where `wayland compositor` can be replaced with `X11` if that's what you're running. Linux doesn't decide what gets keyboard input, and doesn't even really know what a desktop application is. Either `X11` or a `wayland` compositor decides what window has focus and should get keyboard input. 

Note: No parts of Hawck run under root, `inputd` runs with access to the `input` group, which means it has access to raw keyboard input.
