### ISSUE TITLE
Hawk Requires Lua 5.3 but Meson & PKGBUILD Request >=5.3

### ISSUE THREAD

**Issue by JeffCarpenter** [snyball/Hawck#44]
**To Reproduce**
1. Run makepkg -s
2. Linker errors, ie:
```ld.lld: error: undefined symbol: lua_getuservalue                           
>>> referenced by LuaUtils.cpp:62 (../src/LuaUtils.cpp:62)                  
>>>               src/hawck-inputd.p/LuaUtils.cpp.o:(Lua::printStack(lua_State*, std::__cxx11::basic_stringstream<char, std::char_traits<char>, std::allocator<char> >*))                                                           
>>> did you mean: lua_getiuservalue                                         
>>> defined in: /usr/lib/liblua.so
```

**Expected behavior**
Code should link

**Desktop (please complete the following information):**
- Distro: Manjaro Testing
- Version git (directly from repo)
- Method of installation:
  - [x] AUR package
- Keymap:n/a

**Additional context**
Check out [Lua 5.4's API incompatibilities with 5.3.x](https://www.lua.org/manual/5.4/manual.html#8.3)

**Comment by snyball** [comment]
Merged #45
