### ISSUE TITLE
Update LUA dependency for hawck-git AUR package

### ISSUE THREAD

**Issue by MisterY** [snyball/Hawck#46]
Hi, 

The installation of hawck-git fails due to the dependency on lua 5.3 while the current one seems to be 5.4.1.
If no breaking changes, would it be possible to update the build definition? Thanks!

![image](https://user-images.githubusercontent.com/462445/101391968-66d6d480-38c5-11eb-9007-bd6b71b87c08.png)

**Comment by snyball** [comment]
Fixed, thanks for the report.
