### ISSUE TITLE
Convert ahk script to hwk, problems when using capslock as modifier

### ISSUE THREAD

**Issue by ghillb** [snyball/Hawck#48]
I want to convert this [ahk script](https://gist.github.com/ghillb/8a07cec133e22a1f7ac1e689f4932565) to hwk.

Particularly the "caps as modifier part":
```
SetCapsLockState, AlwaysOff

Capslock & RControl::ExitApp

; remapping capslock
#If capsToggle

Capslock & h::Left
Capslock & j::Down
Capslock & k::Up
Capslock & l::Right

Capslock & y::Home
Capslock & u::PgDn
Capslock & i::PgUp
Capslock & o::End

CapsLock & e::Enter
Capslock & b::BS
Capslock & n::Insert
Capslock & m::Del
CapsLock & a::Esc

; close window, close tab
Capslock & q::!F4
Capslock & w::^F4

Capslock & 1::F1
;...

Capslock & Tab::AppsKey
Capslock & Esc::`

; media keys
Capslock & ,::Media_Prev
Capslock & .::Media_Next
Capslock & /::Media_Play_Pause
Capslock & [::Volume_Down
Capslock & ]::Volume_Up
Capslock & \::Volume_Mute
Capslock & p::PrintScreen
```
Is this possible with hawk? Naively, I wanted to try to convert it with the aid of the provided examples, but had no avail.
Can you clarify on this or point me to some resources? I want to understand hawk better and, best case, provide the converted script as an example.

**Hawk installation:**
It is running as intended (example works) on Ubuntu 20.10.

**Comment by snyball** [comment]
Caps (or any other key) as modifier:

```lua
CapsMod = held("Caps")
down + CapsMod + key "q" => --[[ ... ]]--
```

**Comment by ghillb** [comment]
```
CapsMod = held("Caps")
down + CapsMod + key "q" => say "Hopefully this works"
down + CapsMod + key "w" => insert "z"
down + CapsMod + key "a" => insert "b"
```
Oddly, these do not work for me. I only get "Q" and "W" and "A" as output. 

I also tried your advice from [#37 (comment)](https://github.com/snyball/Hawck/issues/37#issuecomment-658735117) and setup logging for key press events.
When I watch the log with `watch -pn 0.1 tail -n 20 /tmp/keylog.txt`, I only see certain key codes: e.g. ctrl (29), alt (56), a(30) work, but caps (58) or s (31) for example do not.

**Comment by snyball** [comment]
@ghillb Did you run `hawck-add` on your script? Keys need to be whitelisted before `inputd` will pass them on to `macrod`.

**Comment by snyball** [comment]
Also, put this at the end before running `hawck-add`:

```lua
key "Caps" => function ()
  kbd:echo()
end
```

So that `hawck-add` will recognize `"Caps"` as a used key.

**Comment by ghillb** [comment]
I put your snippet at the end of the script and run `hawck-add` on the script. The first time I got console output regarding authentication, but no authentication request popped up. The second time nothing at all happened:
```
⮞ hawck-add example.hwk 
New keys added, require authentication for whitelisting them ...
gh@vu : ~/.config/hawck/scripts
⮞ hawck-add example.hwk
```

this is the whole non-functional script now:
```
any => function ()
    local f = io.open("/tmp/keylog.txt", "a")
    f:write(kbd.event_code)
    f:write("\n")
    f:close()
    kbd:echo()
end

CapsMod = held("Caps")
down + CapsMod + key "q" => say "Hopefully this works"
down + CapsMod + key "w" => insert "z"
down + CapsMod + key "a" => insert "b"

key "Caps" => function ()
  kbd:echo()
end

down + ctrl + key "a" => insert "b"
```

I tried running:
```
/usr/lib/policykit-1-gnome/polkit-gnome-authentication-agent-1
```
from [Issue #13](https://github.com/snyball/Hawck/issues/13) and I got:
![Screenshot 2020-12-27 004716](https://user-images.githubusercontent.com/35503959/103168466-c1fc4700-4833-11eb-8d51-ec33803ed9bf.png)
