### ISSUE TITLE
Hawck-inputd producing SystemError: Connection refused

### ISSUE THREAD

**Issue by ghillb** [snyball/Hawck#49]
**To Reproduce**
1. Install Hawck on ubuntu 20.10 via readme instructions for Debian/Ubuntu
2. restart the system
3. inputd produces system error (see screenshot) and hawck is not working

**Expected behavior**
hawck-inputd service runs without errors after restart

**Desktop (please complete the following information):**
- Distro: Ubuntu 20.10
- Version: git
- Method of installation (put X inside [ ] if any of the following apply):
  - [X] `install.sh`
  - [ ] AUR package
- Keymap: [us]
- Keyboard (put X inside [ ] if any of the following apply):
  - [ ] USB
  - [ ] Bluetooth
  - [X] Laptop built-in
  - [ ] I use a USB steering wheel exclusively for all my data input.

**Additional context**  
It worked before the restart as I was successfully running the examples.
![Screenshot 2020-12-27 004716](https://user-images.githubusercontent.com/35503959/103161084-453e7e00-47dd-11eb-961d-c324498440bc.png)

**Comment by snyball** [comment]
```bash
$ hawck-macrod
```

It's just complaining about not being able to connect to `macrod`.

**Comment by ghillb** [comment]
thanks! that was it.
