### ISSUE TITLE
Cannot start daemon due to PID issue

### ISSUE THREAD

**Issue by shkm** [snyball/Hawck#59]
**To Reproduce**
1. Install hawck-git from aur (hawck-git 20210130-1)
2. `./usr/share/hawck/bin/hawck-user-setup`
3. Log out / in
4. `sudo systemctl start hawckd-inputd`
5. Time out

Output of: `systemctl status hawck-inputd.service`

```
● hawck-inputd.service - Hawck input daemon
     Loaded: loaded (/usr/lib/systemd/system/hawck-inputd.service; disabled; vendor preset: disabled)
     Active: activating (start) since Tue 2021-02-16 12:14:30 CET; 3s ago
    Process: 205039 ExecStart=/usr/bin/hawck-inputd (code=exited, status=0/SUCCESS)
      Tasks: 0 (limit: 28066)
     Memory: 4.0K
     CGroup: /system.slice/hawck-inputd.service

Feb 16 12:14:30 Denkpad systemd[1]: Starting Hawck input daemon...
Feb 16 12:14:30 Denkpad hawck-inputd[205039]: Starting Hawck InputD v0.7.1 on:
Feb 16 12:14:30 Denkpad hawck-inputd[205039]:   - </dev/input/event4>
Feb 16 12:14:30 Denkpad hawck-inputd[205039]: forking ...
Feb 16 12:14:30 Denkpad systemd[1]: hawck-inputd.service: Can't open PID file /var/lib/hawck-input/pid (yet?) after start: Operation not permitted
```

I've tried creating the folder / PID file myself but then receive this error:

```
Feb 16 12:38:04 Denkpad systemd[1]: hawck-inputd.service: Failed to parse PID from file /var/lib/hawck-input/pid: Invalid argument
```

**Expected behavior**
Daemon starts up

**Desktop (please complete the following information):**
- Distro: EndeavourOS (Arch)
- Version git
- Method of installation (put X inside [ ] if any of the following apply):
  - [ ] `install.sh`
  - [x] AUR package
- Keymap: us
- Keyboard (put X inside [ ] if any of the following apply):
  - [ ] USB
  - [ ] Bluetooth
  - [ ] Laptop built-in
  - [x] I use a USB steering wheel exclusively for all my data input.

**Comment by snyball** [comment]
@shkm I'm looking into it, there were recently some changes to the build/installation process.

**Comment by maltesa** [comment]
Hi, im experiencing a similar issue. I installed hawck from the aur (git version) and I'm using plain arch, uskeymap, wayland and a built in laptop keyboard. This is my journalctl output:
```
Feb 20 18:40:21 ntbk systemd[1]: Starting Hawck input daemon...
Feb 20 18:40:21 ntbk hawck-inputd[19296]: Starting Hawck InputD v0.7.1 on:
Feb 20 18:40:21 ntbk hawck-inputd[19296]:   - </dev/input/event3>
Feb 20 18:40:21 ntbk hawck-inputd[19296]: forking ...
Feb 20 18:40:21 ntbk hawck-inputd[19298]: Outdated pid file with exe '', continuing ...
Feb 20 18:40:21 ntbk systemd[1]: hawck-inputd.service: Can't open PID file /var/lib/hawck-input/pid (yet?) after start: Operation not permitted
Feb 20 18:40:21 ntbk hawck-inputd[19298]: SystemError: No such file or directory
Feb 20 18:40:21 ntbk systemd[1]: Started Hawck input daemon.
Feb 20 18:40:21 ntbk hawck-inputd[19298]: SystemError: No such file or directory
Feb 20 18:40:22 ntbk hawck-inputd[19298]: SystemError: No such file or directory
Feb 20 18:40:22 ntbk hawck-inputd[19298]: SystemError: No such file or directory
Feb 20 18:40:22 ntbk hawck-inputd[19298]: SystemError: No such file or directory
Feb 20 18:40:22 ntbk hawck-inputd[19298]: SystemError: No such file or directory
...
```

I tried removing the explicit PID file by editing `/usr/lib/systemd/system/hawck-inputd.service` because I found this issue: https://github.com/NixOS/nixpkgs/issues/44307

**Comment by snyball** [comment]
Fixed on Arch Linux now.

PS: After fixing this I found that Arch might need `sudo setfacl -m 'g:uinput:rw' /dev/uinput` before starting `hawck-inputd`, I hadn't rebooted my machine in a while so I don't know when that became necessary.
