### ISSUE TITLE
Feature Request: Support wm_class as a condition for keybindings

### ISSUE THREAD

**Issue by rbreaves** [snyball/Hawck#6]
I apologize if I overlooked something in the existing documentation but I did not find anything explaining how to do this. Autokey supports it via regex, but does not support a negating match, which would also be ideal as it may be easier to specify a few apps that you do not want to have specific keybindings that are otherwise global.

**Comment by snyball** [comment]
This is definately a case of missing documentation, but as Hawck currently does not contain any X11 specific code you'll have to create a custom condition (I'll copy this over to the FAQ later.)

Here's how that would work (untested, I'm on mobile atm) :

```
wm_class = LazyCondF.new(function (pat)
  local p = io.popen("shell command to get wm class")
  local wmc = p:read("*a") 
  p:close() 
  return wmc:find(pat) 
end) 

key "Control_r" + down + wm_class "firefox" => write "something specific to firefox" 
```

Not saying this is ideal, but it works and doesn't tie Hawck to any specific X11 or Wayland features.

See this [Lua string library tutorial](http://lua-users.org/wiki/StringLibraryTutorial) for what is supported by `string.find`.

**Comment by rbreaves** [comment]
Interesting, I have been struggling to find a cross compatible way of pulling the wm_class between x11 and wayland for my own Kinto project.

I ended up using xprop with the spy argument so that I am simply listening for a change in the active window/focus, it's as fast as it possibly could be since it is not polling. The issue with xprop, however, is that it is an x11 specific program that does not work in Wayland.

I have yet to find a method to use in Wayland that listens, I am sure I can find one that polls, but I'd rather avoid that. I have found that using plasmoids in KDE Plasma 5 can pull in the wm_class name and trigger my keymap, but that is DE specific. The KDE plasmoid solution though is very reliable and fast. I believe i3wm can also pull something off under Wayland with a fair amount of ease, but so far I have not found something that works more directly with Wayland, and some of that may be because I am not interested in shell commands for polling for the status.

**Comment by snyball** [comment]
You could try to contact the sway wm project, they might have a Wayland protocol for retrieving the active application.

This is something intentionally left out of the Wayland protocol, for security reasons.

If you end up finding a solution in the form of something that can print the current application wm_class to stdout the example code should do the job.

But I don't think Wayland has any concept of wm_class apart from XWayland backwards compatability. Right now it seems like any solution will be specific to a given compositor.

Closing this issue as retrieving wm_class isn't something Hawck can do on its own for both Wayland and X11.

I'd love to eventually have this built-in at some point in the future however.
