### ISSUE TITLE
Key repetitions support

### ISSUE THREAD

**Issue by mpenet** [snyball/Hawck#60]
I am trying to get my configured keys to repeat when held, is there a way to do this? 

ex with the following config:
```
down + ctrl + key "m" => insert "Return"
```

If I hold ctrl+m it should emit multiple Return signals. I am probably overlooking something.

reading the code it seems right now it's not supported: 

```lua 
-- insert defers to : 
function kbd:pressMod(...)
  local keys = {...}

  self:withCleanMods(function ()
      -- hold mods
      for i = 1, #keys - 1 do
        self:down(keys[i])
      end
     -- press key (down+up) -> I guess we need a loop here that would trigger a repeat after 
     -- delay if held, or maybe handle that directly at kbd:press level 
      self:press(keys[#keys])
     -- release mods
      for i = 1, #keys - 1 do
        self:up(keys[i])
      end
  end)

  udev:flush()
end

```

I see references to   `self.has_repeat = false` and `KeyMode.REPEAT` in the code, so I am wondering if you had already something in mind for this.

**Desktop (please complete the following information):**
- Distro: Ubuntu 20.04.2 LTS
- Version 0.7.1
- Method of installation (put X inside [ ] if any of the following apply):
  - [x] `install.sh`
  - [ ] AUR package
- Keymap: us
- Keyboard (put X inside [ ] if any of the following apply):
  - [x] USB
  - [ ] Bluetooth
  - [x] Laptop built-in
  - [ ] I use a USB steering wheel exclusively for all my data input.

**Comment by snyball** [comment]
@mpenet You want:

```lua
-- -up means anything but key up, including key down and key repeat
-up + key "F1" => insert "j"
```

**Comment by snyball** [comment]
@mpenet Or, if you're exclusively looking for repeats, not key downs:

```lua
-(up / down) + key "F1" => insert "j"
```

**Comment by mpenet** [comment]
Thanks for the pointers. I tried both but there is significant lag when I release the key (it continues to emit the key for a little while). Do you know if that can be tweaked somehow to have it more responsive?

**Comment by snyball** [comment]
@mpenet You probably want to have a look at the `--udev-event-delay` flag for `hawck-inputd` (see the man page,) try setting that to a low number. This requires messing around with the systemd service file, here's how to do that:

```bash
$ systemctl status hawck-inputd
● hawck-inputd.service - Hawck input daemon
     Loaded: loaded (/usr/lib/systemd/system/hawck-inputd.service; disa>
...
# The path is taken from the output of `status`
$ sudo systemctl disable --now hawck-inputd
$ sudo nano /usr/lib/systemd/system/hawck-inputd.service
# Edit the ExecStart line
$ systemctl daemon-reload
$ sudo systemctl enable --now hawck-inputd
```

**Comment by snyball** [comment]
@mpenet It's set to a higher value by default, because certain desktop environments crap out when receiving too many events at the same time. If you're using `sway` then it happens to work with `--udev-event-delay 0`, but GNOME requires a higher number so you might have to experiment a bit.

**Comment by mpenet** [comment]
excellent, thanks.
