### ISSUE TITLE
hawck-input appears on GUI login screen

### ISSUE THREAD

**Issue by BETLOG** [snyball/Hawck#69]
After removing hawck I now see a user: hawck-input appearing as a login option on the KDE login screen GUI (Kubuntu 20.04)
I want to remove it, not just from the login list but from my system entirely.

I have stopped/deleted everything i can think of:
```
sudo systemctl stop hawck-inputd
sudo systemctl disable hawck-inputd
which hawck
groups
sudo groupdel hawck-input-share
sudo rm -rf /etc/hawck
sudo service --status-all
```

**Comment by snyball** [comment]
```
sudo userdel hawck-input
```
