### ISSUE TITLE
Feature Request: Ability to replace only one modifier key

### ISSUE THREAD

**Issue by rbreaves** [snyball/Hawck#7]
Autokey lacks this feature, the ability to rebind only one modifier key on either the left or right side of the keyboard. I currently accomplish this via custom xkb keymap files, but it'd be nice to have alternatives.

**Comment by snyball** [comment]
To clarify, do you mean something like this?

```lua
key "Control_r" => write "something completely different" 
```

AFAIK that should already work.

**Comment by rbreaves** [comment]
Indeed, that is what I am after! Thank you.
