### ISSUE TITLE
Does Hawck support xcape like feature

### ISSUE THREAD

**Issue by QiangF** [snyball/Hawck#8]
With xcape (https://github.com/alols/xcape), you can has a different key binding when a modifier is press and released in a short time. For example, press and release left control send a escape key.

There is a package that combines xcape like feature with an extra keyboard layer:
https://github.com/kozikow/keyremaplinux

The corresponding blog post:
https://kozikow.com/2013/11/15/the-only-alternative-keyboard-layout-youll-ever-need-as-a-programmer/

Can these two features (1. extra layer with a latching modifier; 2 xcape like feature) be done with some kind Hawck configurations?

**Comment by snyball** [comment]
Yes, Hawck can do something like what xcape does, but you'd have to use something like this:

```lua
-- Note: because of how this is implemented, it needs to be put in a separate script,
-- and needs to be the first script to run.
-- It also requires you to enable unsafe mode, as it needs to receive all keyboard input
-- to work.
caps_down = false
caps_as_ctrl = false
up + key "caps" => function ()
  caps_down = false
  if not caps_as_ctrl then
    kbd:press("caps")
  else
    kbd:up("control")
  end
  caps_as_ctrl = false
end

down + key "caps" => function ()
  caps_down = true
  caps_as_ctrl = false
end

down => function ()
  if caps_down and not caps_as_ctrl then
    kbd:down("control")
    caps_as_ctrl = true
  end
  
  kbd:echo()
end
```

This feature seems to be in demand, so I'm also looking into ways to make it easier to do. Maybe something like this:
```lua
key "caps" => multifunction("escape", "control")
```

The alternative keymap, as shown in the blog you linked to can be configured like this:
```lua
-- Bindings inside {} brackets are activated while ctrl_r is held.
ctrl_r => {
  -- For example:
  key "a" => replace "µ"
}
```

**Comment by QiangF** [comment]
Amazing! Can you make the alternative keymap toggle key a latching modifier, I mean when you press and release it, the next key or key combination will be from the alternative keymap, but the next next key will be from the normal layout.

**Comment by QiangF** [comment]
As you see in the above blog post, which I agree totally, but the right alt is awkward to be held with other keys.

**Comment by snyball** [comment]
Yeah, sure:

```lua
latch = false

latch_cond = Cond.new(function()
  local latch_now = latch
  latch = false
  return latch_now
end)

key "control_r" => function ()
  latch = true
end

latch_cond => {
  key "a" => replace "µ"
}
```

**Comment by QiangF** [comment]
This one is cool:
https://github.com/david-janssen/kmonad
