### ISSUE TITLE
Keybinding problem with Apostrophe

### ISSUE THREAD

**Issue by Sonotoki-da** [snyball/hawck#87]
**To Reproduce**
1. Create a new script in `.config/hawck/scripts/`
2. The script code I've tried:
```lua
local unicode_okina = "ʻ"
ctrl + key("apostrophe") => write(unicode_okina)
-- or ctrl + key(40) => write(unicode_okina)
-- or ctrl + key "apostrophe" => write(unicode_okina)
```
3. Restart everything: `sudo systemctl restart hawk-inputd`, launch `hawk-macrod`, add the script `hawk-add script.hwk`

**Expected behavior**
Should insert the unicode okina.

**Desktop (please complete the following information):**
- Distro: Manjaro
- Version: git
- Method of installation (put X inside [ ] if any of the following apply):
  - [ ] `install.sh`
  - [X] AUR package
- Keymap: us
- Keyboard (put X inside [ ] if any of the following apply):
  - [ ] USB
  - [ ] Bluetooth
  - [X] Laptop built-in
  - [ ] I use a USB steering wheel exclusively for all my data input.

**Additional context**
I'm switching to Wayland from X11. In X11, I was using AutoKey to bind `ctrl/alt + apostrophe` to insert specific symbols used in Uzbek ABC.

Like this:
O'zbek (just an apostrpohe) -> Oʻzbek (okina)

The program works with another common keybindings. The example code provided in repo worked as well. But in my case, I couldn't make it work with `apostrophe`. I hope you'll find spare time to look into this.

I appreciate your hard work for creating this environment independent software. Thank you!

**Comment by snyball** [comment]
The parser for keymap files had some bugs, and there may be more. See prior issues about being unable to write the Super key and other keys, some of those issues contain a code snippet that prints out the keymap as it was understood by the parser.

Then just post the output you get here.

**Comment by Sonotoki-da** [comment]
![image](https://github.com/snyball/hawck/assets/34913890/47292be9-e328-46b9-aa61-af58fab490e9)

I was pressing ctrl + apostrophe. I think there are keydown and keyups. That's why the double keypress events.

**Comment by snyball** [comment]
Try this instead https://github.com/snyball/hawck/issues/20#issuecomment-605781789

**Comment by snyball** [comment]
Oh I see what's wrong, you can't just use `write "ʻ"` when the character  `ʻ` isn't part of https://github.com/snyball/hawck/blob/master/keymaps/aliases.lua. The `write` function can only write things that you could type with your keyboard, not just any unicode character.

You can hack this together with a function like this (untested)

```lua
function paste(text)
  local prev = getClipboard()
  setClipboard(text)
  kbd:pressMod("Control", "v") -- paste with ctrl+v
  setClipboard(prev)
end
```

The definition of `setClipboard` and `getClipboard` will depend on whether you're on X11 or Wayland, for Wayland:

```lua
function setClipboard(text)
  local p = io.popen("wl-copy", "w")
  p:write(text)
  p:flush()
  p:close()
end

function getClipboard()
  local p = io.popen("wl-paste", "w")
  local res = p:read("*a")
  p:close()
  return res
end
```

**Comment by Sonotoki-da** [comment]
Ooh, thank you so much! I'm sorry for the late reply, I haven't checked the issues page for a while. I'll try the methods right away
