### ISSUE TITLE
Getting current window information

### ISSUE THREAD

**Issue by jkavalec** [snyball/hawck#89]
I am looking for alternative to AHK/Hammerspoon for Wayland, key macros and remaps are mentioned however I didn't notice anything mentioning window handling.

Is there any way to check the window type/title before performing for instance remapping action?

**Comment by snyball** [comment]
See the `io.popen` Lua function to launch a subprocess, and find whatever command/script needed to get this information from your WM of choice. Search `LazyCondF` in issues for making this into a custom conditional.
